# Generated by Django 2.2.12 on 2020-04-24 03:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonLine', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
